name: Convert JSON
 
on:
  push:
    paths:
      - 'resume.json'

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: kendall
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: index2.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain index2.html)" ]; then
            git add index2.html
            git commit -m "[ci skip] chore(index2.html): update resume page."
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: index2.html
          outputFile: resume2.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Commit converted PDF
        id: commit-pdf
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain resume2.pdf)" ]; then
            git add resume2.pdf
            git commit -m "[ci skip] chore(resume2.pdf): update PDF export."
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
