name: Generate resume
 
on:
  push:
    paths:
      - 'resume.json'
      
env:
  RESOURCE_GROUP: 'RG-Connectivity'
  STORAGE_ACCOUNT: 'stocvrvdwegen'
  CDN_PROFILE: 'sto-vdwegen-cdn'
  CDN_ENDPOINT: 'cv-rvdwegen'

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: rvdwegen/action-jsonresume-convert@v0.1.2-alpha
        name: Export resume as HTML/PDF
        with:
          theme: kendall
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_html_filepath: index.html
          # modifies the resume.pdf in-place
          output_pdf_filepath: resume.pdf
      - name: Commit published HTML/PDF
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain index.html)" ]; then
            git add index.html
            git commit -m "[ci skip] chore(index.html): update resume page."
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          if [ -n "$(git status --porcelain resume.pdf)" ]; then
            git add resume.pdf
            git commit -m "[ci skip] chore(resume.pdf): update resume PDF."
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
         inlineScript: |
            az storage blob upload-batch --overwrite true --account-name $STORAGE_ACCOUNT --auth-mode key -d '$web' -s . --pattern "index.html"
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
         inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name $CDN_PROFILE --name $CDN_ENDPOINT --resource-group $RESOURCE_GROUP
      - name: logout
        run: |
            az logout
