name: Publish resume in JSONResume format as Azure storage static website
 
on: push

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
      - uses: azure/login@v1
        name: Export resume as HTML
        with:
          theme: Kendall
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: index.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain index.html)" ]; then
            git add index.html
            git commit -m "[ci skip] chore(index.html): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          inlineScript: |
              az storage blob upload-batch --overwrite true --account-name staticfilervdw --auth-mode key -d '$web' -s  .
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az cdn endpoint purge --content-paths  "/*" --profile-name staticfilervdw --name rvdwegen-cv --resource-group StaticFileServe
      - name: logout
        run: |
              az logout
        if: always()
